trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '3.x'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: $(dotnetSdkVersion)
  displayName: Use .Net Core $(dotnetSdkVersion) version

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
  displayName: dotnet restore

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: dotnet build

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    publishTestResults: false
  displayName: dotnet test

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  displayName: dotnet publish

- bash: |
    echo "$(Build.ArtifactStagingDirectory)"
    ls -lha $(Build.ArtifactStagingDirectory)
  displayName: Check artifacts  

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: '$(Build.BuildId)'
    publishLocation: 'pipeline'
  displayName: Publish pipeline artifacts
